[book]
authors = ["Hamza Jadid"]
language = "en"
multilingual = false
src = "src"
title = "LibQuiz"
description = "Building a trivia universal library in rust"

[output.html]
cname = "native-rust-lib.ghamza.dev"
default-theme = "light"
git-repository-url = "https://github.com/ghamza-rust/ghamza-rust.github.io"
git-repository-icon = "fa-github"
preferred-dark-theme = "navy"
additional-js = ["./js/code-hl.js", "./js/file-path.js"]

[output.html.playground]
runnable = false

[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
use-data-uris = true
