[book]
authors = ["Ghamza-Jd"]
language = "en"
multilingual = false
src = "src"
title = "Native Rust Library"
description = "Building a Rust library and use it across platforms"

[output.html]
git-repository-url = "https://github.com/ghamza-rust/ghamza-rust.github.io"
git-repository-icon = "fa-github"
cname = "native-rust-lib.ghamza.dev"
google-analytics = "G-M9GYS9Z1XC"
