[book]
src = "src"
title = "Native Rust Library"
authors = ["Ghamza-Jd"]
language = "en"
multilingual = false
description = "Building a Rust library and use it across platforms"

[output.html]
cname = "native-rust-lib.ghamza.dev"
default-theme = "light"
additional-js = ["js/highlighter.js"]
additional-css = ["css/highlighter.css"]
google-analytics = "G-M9GYS9Z1XC"
git-repository-url = "https://github.com/ghamza-rust/ghamza-rust.github.io"
git-repository-icon = "fa-github"
preferred-dark-theme = "light"

[output.html.playground]
runnable = false

[preprocessor.mark]
command="mdbook-mark"
